# Generated by Django 4.2 on 2024-12-05 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_project_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='noti_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='project_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.CharField(blank=True, choices=[('NCE', 'NCE'), ('ND', 'ND'), ('HND', 'HND'), ('Bsc', 'Bsc'), ('PGD', 'PGD'), ('Msc', 'Msc'), ('PhD', 'PhD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='project_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='softwares',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='software_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='softwares',
            name='level',
            field=models.CharField(blank=True, choices=[('NCE', 'NCE'), ('ND', 'ND'), ('HND', 'HND'), ('BSC', 'BSC'), ('PGD', 'PGD'), ('MSC', 'MSC'), ('PHD', 'PHD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='softwares',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='software_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='softwares',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='softwares',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_content',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='project-content'),
        ),
        migrations.AlterField(
            model_name='project',
            name='table_of_content',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='table-of-contents'),
        ),
    ]
