# Generated by Django 4.2 on 2024-12-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userswallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userswallet',
            name='account_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userswallet',
            name='account_number',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userswallet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userswallet',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
