# Generated by Django 4.2 on 2024-12-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cashout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default=True, max_length=50),
        ),
    ]
