# Generated by Django 4.2 on 2024-12-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cashout_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashout',
            options={'verbose_name_plural': 'Cashouts'},
        ),
        migrations.AddField(
            model_name='payments',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project'),
        ),
    ]
